package com.footprint.footprint.db.green;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.footprint.footprint.dbbean.DongtaiShow;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DONGTAI_SHOW".
*/
public class DongtaiShowDao extends AbstractDao<DongtaiShow, Long> {

    public static final String TABLENAME = "DONGTAI_SHOW";

    /**
     * Properties of entity DongtaiShow.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property Code = new Property(3, String.class, "code", false, "CODE");
        public final static Property Time = new Property(4, String.class, "time", false, "TIME");
        public final static Property Beizhu1 = new Property(5, String.class, "beizhu1", false, "BEIZHU1");
        public final static Property Beizhu2 = new Property(6, String.class, "beizhu2", false, "BEIZHU2");
        public final static Property Beizhu3 = new Property(7, String.class, "beizhu3", false, "BEIZHU3");
        public final static Property Beizhu4 = new Property(8, String.class, "beizhu4", false, "BEIZHU4");
        public final static Property StartAdress = new Property(9, String.class, "startAdress", false, "START_ADRESS");
        public final static Property EndAdress = new Property(10, String.class, "endAdress", false, "END_ADRESS");
    }


    public DongtaiShowDao(DaoConfig config) {
        super(config);
    }
    
    public DongtaiShowDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DONGTAI_SHOW\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"TITLE\" TEXT," + // 2: title
                "\"CODE\" TEXT," + // 3: code
                "\"TIME\" TEXT," + // 4: time
                "\"BEIZHU1\" TEXT," + // 5: beizhu1
                "\"BEIZHU2\" TEXT," + // 6: beizhu2
                "\"BEIZHU3\" TEXT," + // 7: beizhu3
                "\"BEIZHU4\" TEXT," + // 8: beizhu4
                "\"START_ADRESS\" TEXT," + // 9: startAdress
                "\"END_ADRESS\" TEXT);"); // 10: endAdress
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DONGTAI_SHOW\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DongtaiShow entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String code = entity.getCode();
        if (code != null) {
            stmt.bindString(4, code);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(5, time);
        }
 
        String beizhu1 = entity.getBeizhu1();
        if (beizhu1 != null) {
            stmt.bindString(6, beizhu1);
        }
 
        String beizhu2 = entity.getBeizhu2();
        if (beizhu2 != null) {
            stmt.bindString(7, beizhu2);
        }
 
        String beizhu3 = entity.getBeizhu3();
        if (beizhu3 != null) {
            stmt.bindString(8, beizhu3);
        }
 
        String beizhu4 = entity.getBeizhu4();
        if (beizhu4 != null) {
            stmt.bindString(9, beizhu4);
        }
 
        String startAdress = entity.getStartAdress();
        if (startAdress != null) {
            stmt.bindString(10, startAdress);
        }
 
        String endAdress = entity.getEndAdress();
        if (endAdress != null) {
            stmt.bindString(11, endAdress);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DongtaiShow entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String code = entity.getCode();
        if (code != null) {
            stmt.bindString(4, code);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(5, time);
        }
 
        String beizhu1 = entity.getBeizhu1();
        if (beizhu1 != null) {
            stmt.bindString(6, beizhu1);
        }
 
        String beizhu2 = entity.getBeizhu2();
        if (beizhu2 != null) {
            stmt.bindString(7, beizhu2);
        }
 
        String beizhu3 = entity.getBeizhu3();
        if (beizhu3 != null) {
            stmt.bindString(8, beizhu3);
        }
 
        String beizhu4 = entity.getBeizhu4();
        if (beizhu4 != null) {
            stmt.bindString(9, beizhu4);
        }
 
        String startAdress = entity.getStartAdress();
        if (startAdress != null) {
            stmt.bindString(10, startAdress);
        }
 
        String endAdress = entity.getEndAdress();
        if (endAdress != null) {
            stmt.bindString(11, endAdress);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DongtaiShow readEntity(Cursor cursor, int offset) {
        DongtaiShow entity = new DongtaiShow( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // code
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // time
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // beizhu1
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // beizhu2
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // beizhu3
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // beizhu4
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // startAdress
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // endAdress
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DongtaiShow entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCode(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTime(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setBeizhu1(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setBeizhu2(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setBeizhu3(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setBeizhu4(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setStartAdress(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setEndAdress(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DongtaiShow entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DongtaiShow entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DongtaiShow entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
